countries = {'AE': 'United Arab Emirates',
             'AF': 'Afghanistan',
             'AU': 'Australia',
             'BN': 'Brunei',
             'BR': 'Brazil',
             'BW': 'Botswana',
             'CA': 'Canada',
             'CH': 'Switzerland', 
             'Christmas Island': 'Australia',
             'CL': 'Chile',
             'CM': 'Cameroon',
             'CN': 'China',
             'Cocos Island': 'Costa Rica',
             'Cocos Islands': 'Costa Rica',
             "Cote D'Ivoire": "Cote d'Ivoire",
             "Cote DIvoire": "Cote d'Ivoire",
             'DE': 'Germany',
             'Dem Rep of the Congo': 'Congo, the Democratic Republic',
             'Democratic Republic of the Congo': 'Congo, the Democratic Republic',
             'Dominican Rep': 'Dominican Republic',
             'ES': 'Spain',
             'GB': 'United Kingdom',
             'GE': 'Georgia',
             'Hong Kong S.A.R., China': 'Hong Kong',
             'ID': 'Indonesia',
             'IN': 'India',
             'IQ': 'Iraq',
             'IT': 'Italy',
             'JP': 'Japan',
             'Korea (South)': 'South Korea',
             'Korea, Republic of': 'South Korea',
             'Korea, South': 'South Korea',
             'KZ': 'Kazakhstan',
             'MA': 'Morocoo',
             'MX': 'Mexico',
             'MY': 'Malaysia',
             'NG': 'Nigeria',
             'No Country Provided': None,
             'NP': 'Nepal',
             'OM': 'Oman',
             'PH': 'Philippines',
             'PK': 'Pakistan',
             'PR': 'United States',
             'RS': 'Serbia',
             'SK': 'Slovakia',
             'Syrian Arab Republic': 'Syria',
             'TR': 'Turkey',
             'U.S. Virgin Islands': 'US Virgin Islands',
             'United States of America': 'United States',
             'US': 'United States',
             'USA': 'United States',
             'VE': 'Venezuela',
             'Vietnam': 'Viet Nam',
             'ZA': 'South Africa',
             'ZM': 'Zambia'
}
