states = {
  '6': None,
  '12': None,
  '57': None,
  '????????????': None,
  '\\-': None,
  '\\--': None,
  '\\-None-': None,
  'Aarhus': None,
  'AB': 'Alberta',
  'Abuja': None,
  'ACT': 'Australian Capital Territory',
  'AE': 'Armed Forces Europe',
  'AGU': 'Aguascalientes',
  'AK': 'Alaska',
  'AL': 'Alabama',
  'AL ': 'Alabama',
  'Albuquerque': None,
  'Alkhwair ': None,
  'Altamonte Springs': None,
  'Andheri (E)': None,
  'AP': 'Andhra Pradesh',
  'Aquitaine': None,
  'AR': 'Arkansas',
  'Armed Forces of Europe': 'Armed Forces Europe',
  'Armenia': None,
  'AS': 'American Samoa',
  'Austin': None,
  'Australia': None,
  'AZ': 'Arizona',
  'B': None,
  'Bahamas': None,
  'Baja California Norte': 'Baja California',
  'Banten': None,
  'BARCELONA': 'Barcelona',
  'Base Digital TV Industry': None,
  'BC': 'British Columbia',
  'BCN': 'Baja California',
  'BCS': 'Baja California Sur',
  'Berlin': 'Berlin',
  'Biscay': 'Biscaia',
  'BN': 'Benevento',
  'British Columbia ': 'British Columbia',
  'British Columnbia': 'British Columbia',
  'Brooklyn': 'New York',
  'Busan': None,
  'CA': 'California',
  'Ca ': 'California',
  'ca': 'California',
  'Ca': 'California',
  'CA 94588': 'California',
  'CAed States': 'California',
  'Cairo': None,
  'Cal': 'California',
  'Calif': 'California',
  'CANADA': None,
  'Centre Region': None,
  'CHH': 'Chihuahua',
  'chi': None,
  'Chicago': 'Illinois',
  'Chonburi': None,
  'Choose a State': None,
  'CHP': 'Chiapas',
  'Chungbuk': None,
  'Chungbuk Provin': None,
  'Chungcheongbuk-': None,
  'CMX': 'Mexico State',
  'CO': 'Colorado',
  'Co': 'Colorado',
  'COA': 'Coahuila',
  'COL': 'Colima',
  'Columbia': None,
  'Comayagua': None,
  'Cortes': None,
  'Costa Rica': None,
  'Cross River': None,
  'CT': 'Connecticut',
  'CT - Connecticut': 'Connecticut',
  'ct': 'Connecticut',
  'Cundinamarca': None,
  'CUNDINAMARCAA': None,
  'D.C.': 'District of Columbia',
  'Dashun 9th Rd.': None,
  'Dc': 'District of Columbia',
  'dc': 'District of Columbia',
  'DC': 'District of Columbia',
  'DE': 'Delaware',
  'De': 'Delaware',
  'DF': 'Federal District',
  'Doha': None,
  'Dripping Springs': None,
  'dub': None,
  'Dubai': None,
  'Dulles': 'Virginia',
  'Edison': None,
  'EME': 'Mexico State',
  'Erbil ': None,
  'FCT': None,
  'Federal Capital Territory': None,
  'FL': 'Florida',
  'Fl': 'Florida',
  'FM': 'Federated Micronesia',
  'FR': None,
  'france': None,
  'GA': 'Georgia',
  'Ga': 'Georgia',
  'Gatineau': 'Quebec',
  'Germany': None,
  'GH': None,
  'Gipuzkoa': 'Guipuzcoa',
  'GOIAS': 'Goiás',
  'Golden': None,
  'Greater London': 'England',
  'GU': 'Guam',
  'GUA': 'Guanajuato',
  'GuangDong': 'Guangdong',
  'Guangdong Province': 'Guangdong',
  'Guangong': 'Guangdong',
  'GUJ': 'Gujarat',
  'Gurgaon': 'Haryana',
  'Gyeonggi': None,
  'HAMPSHIRE': 'England',
  'Heredia': None,
  'HI': 'Hawaii',
  'Huntington Beach': 'California',
  'I am not in the U.S. or Canada': None,
  'IA': 'Iowa',
  'ID': 'Idaho',
  'IL': 'Illinois',
  'Il': 'Illinois',
  'IN': 'Indiana',
  'International': None,
  'Irvine': 'California',
  'Is': None,
  'IS': None,
  'ISHIKAWA': None,
  'İzmir': None,
  'JAL': 'Jalisco',
  'Japan': None,
  'Jia': None,
  'Jiangsu Provinc': 'Jiangsu',
  'Jiangsu Sheng': 'Jiangsu',
  'Jiangxi': 'Jiangxi',
  'Jilin Sheng': 'Jilin',
  'Jonesboro': 'Arkansas',
  'Jonestown': None,
  'Jongno-gu': None,
  'JS': 'Jiangsu',
  'Jung-gu': None,
  'KB': None,
  'KENT': 'England',
  'Kenya': None,
  'Kingston': None,
  'KNO': None,
  'Korea': None,
  'KR': None,
  'KS': 'Kansas',
  'KY': 'Kentucky',
  'Kyoto': None,
  'LA': 'Louisiana',
  'LA.': 'Louisiana',
  'Lagos': None,
  'Lagos State': None,
  'Laguna': None,
  'Latham': None,
  'Leipzig': 'Saxony',
  'LO': 'England',
  'London': 'England',
  'Los Angeles': 'California',
  'MA': 'Massachusetts',
  'Ma': 'Massachusetts',
  'ma': 'Massachusetts',
  'Maharashtra ': 'Maharashtra',
  'MB': 'Manitoba',
  'MD': 'Maryland',
  'Md': 'Maryland',
  'ME': 'Maine',
  'Me': 'Maine',
  'me': 'Maine',
  'Mechanicsburg': 'Pennsylvania',
  'Medina': None,
  'MEX': 'Mexico State',
  'Mexico': 'Mexico State',
  'MH': 'Maharashtra',
  'MI': 'Michigan',
  'MI.': 'Michigan',
  'Miaoli County': None,
  'MIC': 'Michoacán',
  'Michoacan': 'Michoacán',
  'Milano': 'Milan',
  'MN': 'Minnesota',
  'mn': 'Minnesota',
  'MO': 'Missouri',
  'Mo': 'Missouri',
  'mo': 'Missouri',
  'Molina de Segura': 'Murcia',
  'Montreal': 'Quebec',
  'Montreal ': 'Quebec',
  'MP': 'Madhya Pradesh',
  'MS': 'Mississippi',
  'MT': 'Montana',
  'Munich': 'Bavaria',
  'MX': 'Mexico State',
  'n. y.': 'New York',
  'n/a': None,
  'Nairobi': None,
  'Nashville': 'Tennessee',
  'NB': 'New Brunswick',
  'NC': 'North Carolina',
  'nc': 'North Carolina',
  'ND': 'North Dakota',
  'NE': 'Nebraska',
  'Ne': 'Nebraska',
  'ne': 'Nebraska',
  'neptune city': 'New Jersey',
  'Netherlands': None,
  'New York(NY)': 'New York',
  'NH': 'New Hampshire',
  'NJ': 'New Jersey',
  'Nj': 'New Jersey',
  'nj': 'New Jersey',
  'NJ-New Jersey': 'New Jersey',
  'NL': 'Nuevo León',
  'NUEVO LEON': 'Nuevo León',
  'NLE': 'Nuevo León',
  'NM': 'New Mexico',
  'No se requiere para este pas': None,
  'Nordrhein-Westfalen': 'North Rhine-Westphalia',
  'Northamptonshir': 'England',
  'Not required for this country': None,
  'NRB': None,
  'NS': 'Nova Scotia',
  'NSW': 'New South Wales',
  'Nuevo Leon': 'Nuevo León',
  'NV': 'Nevada',
  'NY': 'New York',
  'NY ': 'New York',
  'NY - New York': 'New York',
  'Ny': 'New York',
  'ny': 'New York',
  'OAX': 'Oaxaca',
  'Ocala': 'Florida',
  'OH': 'Ohio',
  'Oh': 'Ohio',
  'oh': 'Ohio',
  'OK': 'Oklahoma',
  'ON': 'Ontario',
  'ont': 'Ontario',
  'OR': 'Oregon',
  'Or': 'Oregon',
  'or': 'Oregon',
  'OR - Oregon': 'Oregon',
  'Osaka': None,
  'ot': None,
  'Other': None,
  'P.R.': 'Puerto Rico',
  'PA': 'Pennsylvania',
  'Pa': 'Pennsylvania',
  'pa': 'Pennsylvania',
  'PAC': None,
  'Philadelphia': 'Pennsylvania',
  'Pichincha': None,
  'PO Box 988': None,
  'PORT HARCOURT': None,
  'Portland': 'Oregon',
  'PR': 'Puerto Rico',
  'Pu': 'Punjab',
  'Pudong': 'Shanghai',
  'PUE': 'Puebla',
  'Pue': 'Puebla',
  'Puerto Rico ': 'Puerto Rico',
  'pun': 'Punjab',
  'QC': 'Quebec',
  'QLD': 'Queensland',
  'QUE': 'Queretaro',
  'RD': None,
  'RI': 'Rhode Island',
  'Rivers State': None,
  'RJ': 'Rajasthan',
  'ROO': 'Quintana Roo',
  'SA': 'South Australia',
  'Safety Harbor': 'Florida',
  'San Francisco': 'California',
  'San Luis Potosi': 'San Luis Potosí',
  'Sao Paulo': 'São Paulo',
  'SC': 'South Carolina',
  'scituate': 'Maine',
  'SD': 'South Dakota',
  'Selangor': None,
  'Seoul': None,
  'Sevilla': 'Seville',
  'Shandong Provin': 'Shandong',
  'Shenzhen': 'Guangdong',
  'SIN': 'Sinaloa',
  'SJ': None,
  'SK': 'Saskatchewan',
  'SLP': 'San Luis Potosí',
  'Somerville': 'Massachusetts',
  'SON': 'Sonora',
  'South Korea': None,
  'Spain': None,
  'Strasskirchen': 'Bavaria',
  'Sweden': None,
  'System': None,
  'Taiwan': None,
  'Tallahassee': 'Florida',
  'TAM': 'Tamaulipas',
  'Tamilnadu': 'Tamil Nadu',
  'Tel Aviv': None,
  'TIBET': 'Xizang',
  'Tijuana': 'Baja California',
  'TJ': 'Baja California',
  'TN': 'Tennessee',
  'Tokyo': None,
  'Toledo': 'Kansas',
  'Toms River': 'New Jersey',
  'Trimulgherry Secunderabad': None,
  'TV': 'Treviso',
  'TX': 'Texas',
  'Tx': 'Texas',
  'tx': 'Texas',
  'UG': None,
  'UK': None,
  'US': None,
  'USA': None,
  'USVI': 'US Virgin Islands',
  'UT': 'Utah',
  'Ut': 'Utah',
  'ut': 'Utah',
  'VA': 'Virginia',
  'Va': 'Virginia',
  'va': 'Virginia',
  'Valhalla': None,
  'VER': 'Veracruz',
  'VI': 'US Virgin Islands',
  'VIC': 'Victoria',
  'VT': 'Vermont',
  'WA': 'Washington',
  'WA.': 'Washington',
  'Washingotn': 'Washington',
  'Wa': 'Washington',
  'wa': 'Washington',
  'Washington DC': 'District of Columbia',
  'Wayne': 'Pennsylvania',
  'Wesley Chapel': 'Florida',
  'West Bloomfield': 'Michigan',
  'West Conshohocken': 'Pennsylvania',
  'WI': 'Wisconsin',
  'Wi': 'Wisconsin',
  'wi': 'Wisconsin',
  'WV': 'West Virginia',
  'WY': 'Wyoming',
  'Yavne': None,
  'Yongin-si  Gyeo': None,
  'YT': 'Yukon',
  'YUC': 'Yucatán',
  'Yucatan': 'Yucatán',
  'Yunlin County': None,
  'Zhejiang provin': 'Zhejiang',
  '8:29': None,
  '8:29:00 AM': None,
  '1/14/2013': None,
}
