country_states = {
  'United States': ['Armed Forces Americas', 'Armed Forces Europe', 'Alaska', 'Alabama', 'Armed Forces Pacific', 'Arkansas', 'American Samoa', 'Arizona', 'California', 'Colorado', 'Connecticut', 'District of Columbia', 'Delaware', 'Florida', 'Federated Micronesia', 'Georgia', 'Guam', 'Hawaii', 'Iowa', 'Idaho', 'Illinois', 'Indiana', 'Kansas', 'Kentucky', 'Louisiana', 'Massachusetts', 'Maryland', 'Maine', 'Marshall Islands', 'Michigan', 'Minnesota', 'Missouri', 'Northern Mariana Islands', 'Mississippi', 'Montana', 'North Carolina', 'North Dakota', 'Nebraska', 'New Hampshire', 'New Jersey', 'New Mexico', 'Nevada', 'New York', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico', 'Palau', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'United States Minor Outlying Islands', 'Utah', 'Virginia', 'US Virgin Islands', 'Vermont', 'Washington', 'Wisconsin', 'West Virginia', 'Wyoming'],
  'China': ['Beijing', 'Tianjin', 'Hebei', 'Shanxi', 'Nei Mongol', 'Liaoning', 'Jilin', 'Heilongjiang', 'Shanghai', 'Jiangsu', 'Zhejiang', 'Anhui', 'Fujian', 'Jiangxi', 'Shandong', 'Henan', 'Hubei', 'Hunan', 'Guangdong', 'Guangxi', 'Hainan', 'Chongqing', 'Sichuan', 'Guizhou', 'Yunnan', 'Xizang', 'Shaanxi', 'Gansu', 'Qinghai', 'Ningxia', 'Xinjiang', 'Taiwan', 'Hong Kong', 'Macao'],
  'Spain': [],
  'Germany': [],
  'United Kingdom': [],
  'Mexico': ['Aguascalientes', 'Baja California', 'Baja California Sur', 'Chihuahua', 'Colima', 'Campeche', 'Coahuila', 'Chiapas', 'Federal District', 'Durango', 'Guerrero', 'Guanajuato', 'Hidalgo', 'Jalisco', 'Mexico State', 'Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana Roo', 'Sinaloa', 'San Luis Potosí', 'Sonora', 'Tabasco', 'Tlaxcala', 'Tamaulipas', 'Veracruz', 'Yucatán', 'Zacatecas'],
  'Canada': ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 'Nova Scotia', 'Northwest Territories', 'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon Territories'],
  'Italy': ['Argigento', 'Alessandria', 'Ancona', 'Aosta', 'Ascoli Piceno', "L'Aquila", "Arezzo", "Asti", "Avellino", "Bari", "Bergamo", "Biella", "Belluno", "Benevento", "Bologna", "Brindisi", "Brescia", "Barletta-Andria-Trani", "Bolzano", "Cagliari", "Campobasso", "Caserta", "Chieti", "Carbona-Iglesias", "Caltanissetta", "Cuneo", "Como", "Cremona", "Cosenza", "Catania", "Catanzaro", "Enna", "Forli-Cesena", "Ferrara", "Foggia", "Florence", "Fermo", "Frosinone", "Genoa", "Gorizia", "Grosseto", "Imperia", "Isernia", "Crotone", "Lecco", "Lecce", "Livorno", "Lodi", "Latina", "Lucca", "Monza and Brianza", "Macereta", "Messina", "Milan", "Mantua", "Modena", "Massa and Carrara", "Matera", "Naples", "Novara", "Nuoro", "Ogliastra", "Oristano", "Olbia-Tempio", "Palermo", "Piacenza", "Padua", "Pescara", "Perugia", "Pisa", "Pordenone", "Prato", "Parma", "Pistoia", "Pesaro and Urbino", "Pavia", "Potenza", "Ravenna", "Reggio Calabria", "Reggio Emilia", "Ragusa", "Rieti", "Rome", "Rimini", "Rovigo", "Salerno", "Siena", "Sondrio", "La Spezia", "Syracuse", "Sassari", "Savona", "Taranto", "Teramo", "Trento", "Turin", "Trapani", "Terni", "Trieste", "Treviso", "Udine", "Varese", "Verbano-Cusio-Ossola", "Vercelli", "Venice", "Vicenza", "Verona", "Medio Campidano", "Viterbo", "Vibo Valentia"],
  'Australia': ['Australian Capital Territory', 'New South Wales', 'Northern Territory', 'Queensland', 'South Australia', 'Tasmania', 'Victoria', 'Western Australia'],
  'India': ['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Daman and Diu', 'Delhi', 'Dadra and Nagar Haveli', 'Goa', 'Gujarat', 'Himachal Pradesh', 'Haryana', 'Jharkhand', 'Jammu and Kashmir', 'Karnataka', 'Kerala', 'Lakshadweep', 'Maharashtra', 'Meghalaya', 'Manipur', 'Madhya Pradesh', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Puducherry', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
  'Brazil': ['Acre', 'Alagoas', 'Amazonas', 'Amapá', 'Bahia', 'Ceará', 'Distrito Federal', 'Espírito Santo', 'Goiás', 'Maranhão', 'Minas Gerais', 'Mato Grosso do Sul', 'Mato Grosso', 'Pará', 'Paraíba', 'Pernambuco', 'Piauí', 'Paraná', 'Rio de Janeiro', 'Rio Grande do Norte', 'Rondônia', 'Roraima', 'Rio Grande do Sul', 'Santa Catarina', 'Sergipe', 'São Paulo', 'Tocantins'],
  'Ireland': ['Clare', 'Cavan', 'Cork', 'Carlow', 'Dublin', 'Donegal', 'Galway', 'Kildare', 'Kilkenny', 'Kerry', 'Longford', 'Louth', 'Limerick', 'Leitrim', 'Laois', 'Meath', 'Monaghan', 'Mayo', 'Offaly', 'Roscommon', 'Sligo', 'Tipperary', 'Waterford', 'Westmeath', 'Wicklow', 'Wexford']
}
